import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    // ─── Nav ───
    brand_sub: "Verified PGs & Co-Living",
    explore_pgs: "Explore PGs",
    find_roommates: "Find Roommates",
    how_it_works: "How It Works",
    list_your_pg: "List Your PG",
    admin_panel: "Admin Panel",
    sign_in: "Sign In",
    student_signup: "Student Sign Up",
    logout: "Logout",
    my_dashboard: "My Dashboard",
    select_campus: "Select Campus / Area",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",

    // ─── Hero & Search ───
    hero_title: "Verified Student Living",
    co_living: "Near Your Campus",
    hero_subtitle: "Discover verified student PGs, hostels & co-living spaces audited by our 42-point physical safety check. Move in with zero brokerage.",
    search_placeholder: "Enter college, campus gate, or locality (e.g. GEC Kumarbagh)...",
    search_btn: "Find Verified Rooms",
    zero_brokerage: "Zero Brokerage",
    verified_rooms: "Verified Accommodation",
    trust_pill: "100% In-Person Audited Accommodations • Zero Brokerage Guaranteed",
    near_live_location: "Near My Live Location (10 km)",
    popular_label: "Popular:",
    popular_campuses_dropdown: "Popular Campuses & Cities",
    all_gender: "All Types (Boys / Girls / Co-ed)",
    boys_only: "Boys Only",
    girls_only: "Girls Only",
    co_ed: "Co-ed Living",
    any_budget: "Any Budget",
    metric_beds: "Verified Student Beds",
    metric_brokerage: "Zero Brokerage Always",
    metric_reviews: "Student Reviews",
    metric_audit: "42-Point Physical Audit",

    // ─── Categories ───
    popular_accommodation_types: "Popular Accommodation Types",
    explore_verified_rooms: "Explore verified rooms curated for your lifestyle and budget.",
    browse_all: "Browse All",
    boys_pg_hostels: "Boys PG & Hostels",
    boys_pg_desc: "3 meals, Wi-Fi & study environment",
    boys_only_tag: "Boys Only",
    girls_pg_hostels: "Girls PG & Hostels",
    girls_pg_desc: "Safe, gated with 24x7 warden & CCTV",
    girls_safe_tag: "100% Safe & Gated",
    pg_with_meals: "PG with 3 Meals",
    pg_meals_desc: "Breakfast, lunch, and dinner included",
    homely_food_tag: "Homely Food",
    private_rooms: "Private Single Rooms",
    private_rooms_desc: "Personal space with attached washroom",
    full_privacy_tag: "Full Privacy",

    // ─── Explore by City ───
    explore_by_city: "Explore PGs by City & Campus",
    explore_by_city_sub: "Find verified student PGs and hostels within walking distance of key gates.",

    // ─── Verified Listings Feed ───
    verified_pgs_near: "Verified PGs & Co-Living Spaces Near You",
    verified_pgs_sub: "100% Verified owners • Physical inspection passed • Direct WhatsApp to landlords",
    all_pgs: "All PGs",
    meals_included: "Meals Included",
    boys_pg: "Boys PG",
    girls_pg: "Girls PG",
    single_room: "Single Room",
    no_match_filter: "No accommodations match this filter",
    reset_filters: "Reset Filters",

    // ─── 5-Point Audit ───
    audit_badge: "The 5-Point RoomNest Audit Standard",
    audit_title: "What We Physically Inspect Before Listing",
    audit_sub: "Every PG is physically audited to verify the building exterior, bedroom comfort, study desk, washroom, and mess meals.",
    genuine_photos: "100% Genuine Photos",
    audit_1: "1. Building Front Look",
    audit_1_sub: "Gated entry, street lighting & curfew gate",
    audit_2: "2. Clean Student Bedroom",
    audit_2_sub: "Comfortable mattress, ventilation & wardrobe",
    audit_3: "3. Study Table & Wi-Fi",
    audit_3_sub: "Dedicated desk, task light & 50+ Mbps net",
    audit_4: "4. Attached Washroom",
    audit_4_sub: "Clean tiles, running water & hot geyser",
    audit_5: "5. Hygienic Mess Hall",
    audit_5_sub: "Fresh meals, dining tables & UV/RO water",
    inspected_by: "Inspected by Campus Team",

    // ─── Why RoomNest ───
    advantage_label: "The RoomNest Advantage",
    advantage_title: "Why Students & Parents Trust RoomNest",
    advantage_sub: "We solve the biggest challenges in student housing with complete transparency.",
    verified_owners: "100% Verified Owners",
    verified_owners_desc: "Every host is verified with government ID (Aadhaar/PAN) and in-person property audits.",
    zero_brokerage_title: "Zero Brokerage Always",
    zero_brokerage_desc: "No middleman commission. Connect directly with landlords on WhatsApp with complete rent transparency.",
    homely_meals: "Homely 3 Meals & RO Water",
    homely_meals_desc: "Weekly audited student mess halls, fresh vegetables, hygienic kitchens, and UV+RO drinking water.",
    safe_campus: "Safe Gated Campuses",
    safe_campus_desc: "Street lighting, night curfew locks, CCTV cameras, and 24/7 security guards for student safety.",

    // ─── FAQ ───
    faq_label: "Got Questions?",
    faq_title: "Frequently Asked Questions",
    faq_1_q: "How does RoomNest verify PG owners and properties?",
    faq_1_a: "Every room listed on RoomNest undergoes a physical 5-point in-person audit by our campus team. We verify the landlord's government ID (Aadhaar/PAN), inspect the exterior building gate, bedroom furniture, study table, geyser, and taste the student mess food before approving the listing.",
    faq_2_q: "Is there any brokerage fee to book or contact the owner?",
    faq_2_a: "Zero! There is absolutely Rs.0 brokerage. You connect directly with the verified property owner or warden on WhatsApp or via call with complete price transparency.",
    faq_3_q: "Can I find accommodations within 10 km of my live location?",
    faq_3_a: "Yes! Click the 'Near My Live Location' button or the GPS icon inside the search bar. The platform will automatically calculate distances and show verified PGs and hostels within a 10 km radius.",
    faq_4_q: "Do PGs provide rent agreements for college address proof?",
    faq_4_a: "Yes, our verified partner PGs provide formal rent agreements upon move-in, which students can submit for college registration, bank accounts, or scholarship applications.",

    // ─── CTA Banner ───
    cta_label: "For PG Owners & Wardens",
    cta_title: "Own a student PG or hostel near campus?",
    cta_desc: "List for free, get verified by our physical audit team, and receive direct WhatsApp inquiries from 1,000+ college students. Zero listing fee.",
    cta_btn: "List Your PG Free",

    // ─── Room & Distance ───
    campus_proximity: "Campus Proximity",
    live_map_title: "Live GPS Route & Distance Map",
    live_location: "Your Live Location",
    room_location: "Selected Accommodation",
    campus_gate: "College / University Gate",
    distance_you_to_room: "Live GPS to Room",
    distance_room_to_campus: "Room to Campus Gate",
    walking_time: "Walking Time",
    cycling_time: "Bicycle Time",
    driving_transit: "Driving / Auto",
    gps_active: "Live GPS Active",
    gps_locating: "Locating your live position...",
    gps_enable: "Enable Live GPS",
    gps_refresh: "Refresh Live GPS",
    google_maps_route: "Open in Google Maps",
    to_room_directions: "Directions to Room",
    to_campus_directions: "Directions to Campus",

    // ─── Visit Schedule ───
    schedule_visit_title: "Schedule Free Campus Visit",
    book_visit_slot: "Book Visit Slot",
    visit_success_msg: "Visit scheduled! The owner has been notified via WhatsApp.",
    verified_owner: "Property Verified Owner",
    call_owner: "Call Owner",
    whatsapp_owner: "WhatsApp",
    in_app_chat: "In-app Chat",
    rent_breakdown: "Transparent Cost Breakdown",
    per_month: "/ month",
    deposit: "Security Deposit",
    food_included: "Food / Mess Included",
    curfew_timing: "Gate Timings & Curfew",
    facilities: "Facilities & Student Amenities",
    write_review: "Write Review",

    // ─── Room Card ───
    verified_owner_badge: "100% Verified Owner",
    meals_included_badge: "3 Meals Included",
    walk_min: "min walk",
    per_mo: "/mo",
    view_details: "View Details",
    whatsapp_now: "WhatsApp Now",
    compare: "Compare",
    zero_brokerage_badge: "Zero Brokerage",
    food_mess: "Food/Mess",
    study_desk: "Study Desk",
    wifi_label: "Wi-Fi",
    beds_available: "beds available",

    // ─── Login ───
    login_title: "Student & Owner Login",
    login_sub: "Access verified listings, campus visits, and owner chats.",
    email_placeholder: "Email address",
    password_placeholder: "Password",
    forgot_password: "Forgot password?",
    login_btn: "Log in",
    logging_in: "Logging in...",
    new_to_roomnest: "New to RoomNest?",
    create_account: "Create an account",

    // ─── Register ───
    register_title: "Create Your Account",
    register_sub: "Join RoomNest to find your perfect accommodation",
    full_name: "Full Name",
    phone_number: "Phone Number",
    confirm_password: "Confirm Password",
    register_as: "Register as",
    student_tenant: "Student / Tenant",
    pg_owner: "PG Owner / Warden",
    register_btn: "Create Account",
    registering: "Creating account...",
    already_have_account: "Already have an account?",
    sign_in_link: "Sign in",

    // ─── Footer ───
    footer_popular_campuses: "Popular Campuses",
    footer_student_living: "Student Living",
    footer_find_rooms: "Find Campus Rooms",
    footer_find_roommate: "Find a Roommate",
    footer_rent_guide: "Rent Agreement Guide",
    footer_zero_brokerage: "Zero Brokerage Policy",
    footer_owners: "Property Owners & Staff",
    footer_list_pg: "List Student PG / Room",
    footer_owner_verify: "Owner Verification Process",
    footer_owner_dashboard: "Owner Dashboard",
    footer_admin_portal: "Admin Approval Portal",
    footer_tagline: "Verified Student Accommodations",
    footer_desc: "Helping college students find verified PGs, hostels, and rental rooms near their campuses with zero brokerage, transparent mess & utility costs, and student peer reviews.",
    footer_audited: "100% In-Person Audited",
    footer_zero_brokerage_badge: "Zero Brokerage",
    footer_copyright: "RoomNest India. Built for college students nationwide.",
    footer_safety: "Safety Standards",
    footer_rent_support: "Rent Agreement Support",

    // ─── Search Page ───
    search_results: "Search Results",
    filters: "Filters",
    sort_by: "Sort by",
    distance_low: "Distance: Low to High",
    price_low: "Price: Low to High",
    price_high: "Price: High to Low",
    rating_high: "Rating: High to Low",
    newest_first: "Newest First",
    campus_college: "Campus / College",
    room_type: "Room Type",
    occupancy_type: "Occupancy",
    max_distance: "Max Distance",
    price_range: "Price Range",
    min_rent: "Min Rent",
    max_rent: "Max Rent",
    amenities: "Amenities",
    food_included_filter: "Food / Mess Included",
    verified_only: "Verified Only",
    rent_agreement: "Rent Agreement",
    apply_filters: "Apply Filters",
    clear_all: "Clear All",
    showing_results: "Showing results",
    no_rooms_found: "No rooms found",
    try_different: "Try different filters or search terms",
    load_more: "Load More",

    // ─── RoomBuddy AI ───
    ai_name: "RoomBuddy",
    ai_tagline: "AI Room Finding Assistant",
    ai_greeting: "Hi! I'm RoomBuddy. I can help you find the perfect PG or room. Try saying 'Find boys PG near GEC' or 'Show rooms under 4000'!",
    ai_listening: "Listening... Speak now",
    ai_placeholder: "Type or speak to find rooms...",
    ai_speak: "SPEAK",
    ai_close: "Close",
    ai_quick_boys: "Boys PG near campus",
    ai_quick_girls: "Girls PG with meals",
    ai_quick_budget: "Rooms under Rs.4000",
    ai_quick_single: "Private single rooms",
  },

  hi: {
    brand_sub: "सत्यापित पीजी और हॉस्टल",
    explore_pgs: "पीजी खोजें",
    find_roommates: "रूममेट खोजें",
    how_it_works: "यह कैसे काम करता है",
    list_your_pg: "अपना पीजी लिस्ट करें",
    admin_panel: "एडमिन पैनल",
    sign_in: "लॉग इन",
    student_signup: "छात्र साइन अप",
    logout: "लॉग आउट",
    my_dashboard: "मेरा डैशबोर्ड",
    select_campus: "कैंपस / क्षेत्र चुनें",
    dark_mode: "डार्क मोड",
    light_mode: "लाइट मोड",
    hero_title: "सत्यापित छात्र आवास",
    co_living: "आपके कैंपस के पास",
    hero_subtitle: "42-बिंदु भौतिक सुरक्षा जांच द्वारा सत्यापित पीजी, हॉस्टल और निजी कमरे खोजें। शून्य ब्रोकरेज गारंटी।",
    search_placeholder: "कॉलेज, गेट या इलाका खोजें (उदा. जीईसी कुमारबाग)...",
    search_btn: "सत्यापित कमरे खोजें",
    zero_brokerage: "शून्य ब्रोकरेज",
    verified_rooms: "सत्यापित आवास",
    trust_pill: "100% व्यक्तिगत रूप से जांचे गए आवास • शून्य ब्रोकरेज गारंटी",
    near_live_location: "मेरी लाइव लोकेशन के पास (10 किमी)",
    popular_label: "लोकप्रिय:",
    popular_campuses_dropdown: "लोकप्रिय कैंपस और शहर",
    all_gender: "सभी प्रकार (लड़के / लड़कियां / को-एड)",
    boys_only: "केवल लड़के",
    girls_only: "केवल लड़कियां",
    co_ed: "सह-शिक्षा (Co-ed)",
    any_budget: "कोई भी बजट",
    metric_beds: "सत्यापित छात्र बेड",
    metric_brokerage: "हमेशा शून्य ब्रोकरेज",
    metric_reviews: "छात्र समीक्षाएं",
    metric_audit: "42-बिंदु भौतिक जांच",
    popular_accommodation_types: "लोकप्रिय आवास प्रकार",
    explore_verified_rooms: "आपकी जीवनशैली और बजट के अनुसार सत्यापित कमरे।",
    browse_all: "सभी देखें",
    boys_pg_hostels: "लड़कों का पीजी और हॉस्टल",
    boys_pg_desc: "3 बार भोजन, वाई-फाई और पढ़ाई का माहौल",
    boys_only_tag: "केवल लड़के",
    girls_pg_hostels: "लड़कियों का पीजी और हॉस्टल",
    girls_pg_desc: "सुरक्षित, गेटेड कैंपस, 24x7 वॉर्डन और CCTV",
    girls_safe_tag: "100% सुरक्षित और गेटेड",
    pg_with_meals: "3 बार भोजन वाला पीजी",
    pg_meals_desc: "नाश्ता, दोपहर और रात का खाना शामिल",
    homely_food_tag: "घर जैसा खाना",
    private_rooms: "प्राइवेट सिंगल रूम",
    private_rooms_desc: "अटैच्ड बाथरूम के साथ निजी कमरा",
    full_privacy_tag: "पूर्ण प्राइवेसी",
    explore_by_city: "शहर और कैंपस के अनुसार पीजी खोजें",
    explore_by_city_sub: "प्रमुख गेटों के पास सत्यापित छात्र पीजी और हॉस्टल खोजें।",
    verified_pgs_near: "आपके पास सत्यापित पीजी और को-लिविंग",
    verified_pgs_sub: "100% सत्यापित मालिक • भौतिक जांच पास • मालिक से सीधे व्हाट्सएप",
    all_pgs: "सभी पीजी",
    meals_included: "भोजन शामिल",
    boys_pg: "लड़कों का पीजी",
    girls_pg: "लड़कियों का पीजी",
    single_room: "सिंगल रूम",
    no_match_filter: "इस फ़िल्टर से कोई आवास नहीं मिला",
    reset_filters: "फ़िल्टर रीसेट करें",
    audit_badge: "रूमनेस्ट 5-पॉइंट ऑडिट स्टैंडर्ड",
    audit_title: "लिस्ट करने से पहले हम क्या जांचते हैं",
    audit_sub: "हर पीजी की बिल्डिंग, बेडरूम, स्टडी डेस्क, बाथरूम और मेस खाने की भौतिक जांच होती है।",
    genuine_photos: "100% असली फ़ोटो",
    audit_1: "1. बिल्डिंग का फ्रंट लुक",
    audit_1_sub: "गेटेड एंट्री, स्ट्रीट लाइटिंग और कर्फ्यू गेट",
    audit_2: "2. साफ-सुथरा छात्र बेडरूम",
    audit_2_sub: "आरामदायक गद्दा, हवादार और अलमारी",
    audit_3: "3. स्टडी टेबल और वाई-फाई",
    audit_3_sub: "स्टडी डेस्क, लैंप और 50+ Mbps इंटरनेट",
    audit_4: "4. अटैच्ड बाथरूम",
    audit_4_sub: "साफ टाइल्स, बहता पानी और गीज़र",
    audit_5: "5. स्वच्छ मेस हॉल",
    audit_5_sub: "ताज़ा भोजन, डाइनिंग टेबल और UV/RO पानी",
    inspected_by: "कैंपस टीम द्वारा जांचा गया",
    advantage_label: "रूमनेस्ट एडवांटेज",
    advantage_title: "छात्र और अभिभावक रूमनेस्ट पर भरोसा क्यों करते हैं",
    advantage_sub: "हम छात्र आवास की सबसे बड़ी चुनौतियों को पारदर्शिता से हल करते हैं।",
    verified_owners: "100% सत्यापित मालिक",
    verified_owners_desc: "हर मालिक का सरकारी आईडी (आधार/पैन) और व्यक्तिगत संपत्ति जांच द्वारा सत्यापन।",
    zero_brokerage_title: "हमेशा शून्य ब्रोकरेज",
    zero_brokerage_desc: "कोई बिचौलिया नहीं। व्हाट्सएप पर मालिक से सीधे बात करें, पूर्ण किराया पारदर्शिता।",
    homely_meals: "3 बार घर जैसा भोजन और RO पानी",
    homely_meals_desc: "हफ्ते में जांचा जाने वाला मेस, ताज़ी सब्ज़ियां, स्वच्छ रसोई और UV+RO पानी।",
    safe_campus: "सुरक्षित गेटेड कैंपस",
    safe_campus_desc: "स्ट्रीट लाइटिंग, रात का कर्फ्यू, CCTV कैमरे और 24/7 सुरक्षा गार्ड।",
    faq_label: "कोई सवाल है?",
    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    faq_1_q: "रूमनेस्ट पीजी मालिकों और संपत्तियों को कैसे सत्यापित करता है?",
    faq_1_a: "रूमनेस्ट पर लिस्ट होने वाले हर कमरे की कैंपस टीम द्वारा 5-पॉइंट भौतिक जांच होती है। हम मालिक का सरकारी आईडी, बिल्डिंग गेट, बेडरूम, स्टडी टेबल, गीज़र सत्यापित करते हैं और मेस का खाना चखकर ही लिस्टिंग स्वीकृत करते हैं।",
    faq_2_q: "क्या कोई ब्रोकरेज शुल्क है?",
    faq_2_a: "बिल्कुल नहीं! शून्य ब्रोकरेज। आप सीधे सत्यापित मालिक या वॉर्डन से व्हाट्सएप या कॉल पर संपर्क करें, पूर्ण मूल्य पारदर्शिता के साथ।",
    faq_3_q: "क्या मैं अपनी लाइव लोकेशन से 10 किमी के अंदर आवास खोज सकता/सकती हूं?",
    faq_3_a: "हां! 'मेरी लाइव लोकेशन के पास' बटन या सर्च बार में GPS आइकन पर क्लिक करें। प्लेटफॉर्म स्वचालित रूप से दूरी की गणना करके 10 किमी के भीतर सत्यापित पीजी दिखाएगा।",
    faq_4_q: "क्या पीजी कॉलेज एड्रेस प्रूफ के लिए किराया समझौता देते हैं?",
    faq_4_a: "हां, हमारे सत्यापित पार्टनर पीजी मूव-इन पर औपचारिक किराया समझौता प्रदान करते हैं, जिसे छात्र कॉलेज पंजीकरण, बैंक खाते या छात्रवृत्ति आवेदन के लिए जमा कर सकते हैं।",
    cta_label: "पीजी मालिकों और वॉर्डन के लिए",
    cta_title: "कैंपस के पास छात्र पीजी या हॉस्टल है?",
    cta_desc: "मुफ्त में लिस्ट करें, हमारी ऑडिट टीम से सत्यापन करवाएं, और 1,000+ छात्रों से सीधे व्हाट्सएप पूछताछ प्राप्त करें। शून्य लिस्टिंग शुल्क।",
    cta_btn: "मुफ्त में पीजी लिस्ट करें",
    campus_proximity: "कैंपस से नजदीकी",
    live_map_title: "लाइव जीपीएस रूट और दूरी मैप",
    live_location: "आपकी लाइव लोकेशन",
    room_location: "चुना हुआ पीजी / रूम",
    campus_gate: "कॉलेज / यूनिवर्सिटी गेट",
    distance_you_to_room: "आपकी लोकेशन से रूम तक",
    distance_room_to_campus: "रूम से कॉलेज गेट तक",
    walking_time: "पैदल समय",
    cycling_time: "साइकिल से",
    driving_transit: "ऑटो / बाइक",
    gps_active: "लाइव जीपीएस कनेक्टेड",
    gps_locating: "आपकी लोकेशन ट्रैक की जा रही है...",
    gps_enable: "लाइव जीपीएस चालू करें",
    gps_refresh: "जीपीएस रीफ़्रेश करें",
    google_maps_route: "गूगल मैप्स पर रूट खोलें",
    to_room_directions: "रूम तक का रास्ता",
    to_campus_directions: "कॉलेज तक का रास्ता",
    schedule_visit_title: "मुफ़्त कैंपस विज़िट शेड्यूल करें",
    book_visit_slot: "विज़िट स्लॉट बुक करें",
    visit_success_msg: "विज़िट बुक हो गई! रूम मालिक को व्हाट्सएप पर सूचना भेज दी गई है।",
    verified_owner: "सत्यापित रूम मालिक",
    call_owner: "कॉल करें",
    whatsapp_owner: "व्हाट्सएप",
    in_app_chat: "ऐप में चैट",
    rent_breakdown: "किराया विवरण",
    per_month: "/ महीना",
    deposit: "सिक्योरिटी डिपॉज़िट",
    food_included: "खाना / मेस शामिल",
    curfew_timing: "गेट बंद होने का समय",
    facilities: "सुविधाएं और एमेनिटीज",
    write_review: "रिव्यू लिखें",
    verified_owner_badge: "100% सत्यापित मालिक",
    meals_included_badge: "3 बार भोजन शामिल",
    walk_min: "मिनट पैदल",
    per_mo: "/माह",
    view_details: "विवरण देखें",
    whatsapp_now: "व्हाट्सएप करें",
    compare: "तुलना करें",
    zero_brokerage_badge: "शून्य ब्रोकरेज",
    food_mess: "भोजन/मेस",
    study_desk: "स्टडी डेस्क",
    wifi_label: "वाई-फाई",
    beds_available: "बेड उपलब्ध",
    login_title: "छात्र और मालिक लॉगिन",
    login_sub: "सत्यापित लिस्टिंग, कैंपस विज़िट और मालिक चैट एक्सेस करें।",
    email_placeholder: "ईमेल पता",
    password_placeholder: "पासवर्ड",
    forgot_password: "पासवर्ड भूल गए?",
    login_btn: "लॉग इन करें",
    logging_in: "लॉग इन हो रहा है...",
    new_to_roomnest: "रूमनेस्ट पर नए हैं?",
    create_account: "अकाउंट बनाएं",
    register_title: "अपना अकाउंट बनाएं",
    register_sub: "सही आवास खोजने के लिए रूमनेस्ट से जुड़ें",
    full_name: "पूरा नाम",
    phone_number: "फ़ोन नंबर",
    confirm_password: "पासवर्ड की पुष्टि करें",
    register_as: "इस रूप में रजिस्टर करें",
    student_tenant: "छात्र / किरायेदार",
    pg_owner: "पीजी मालिक / वॉर्डन",
    register_btn: "अकाउंट बनाएं",
    registering: "अकाउंट बन रहा है...",
    already_have_account: "पहले से अकाउंट है?",
    sign_in_link: "लॉग इन करें",
    footer_popular_campuses: "लोकप्रिय कैंपस",
    footer_student_living: "छात्र जीवन",
    footer_find_rooms: "कैंपस रूम खोजें",
    footer_find_roommate: "रूममेट खोजें",
    footer_rent_guide: "किराया समझौता गाइड",
    footer_zero_brokerage: "शून्य ब्रोकरेज नीति",
    footer_owners: "संपत्ति मालिक और स्टाफ",
    footer_list_pg: "छात्र पीजी / रूम लिस्ट करें",
    footer_owner_verify: "मालिक सत्यापन प्रक्रिया",
    footer_owner_dashboard: "मालिक डैशबोर्ड",
    footer_admin_portal: "एडमिन अप्रूवल पोर्टल",
    footer_tagline: "सत्यापित छात्र आवास",
    footer_desc: "कॉलेज छात्रों को शून्य ब्रोकरेज, पारदर्शी मेस और यूटिलिटी लागत, और छात्र समीक्षाओं के साथ सत्यापित पीजी, हॉस्टल और किराये के कमरे खोजने में मदद।",
    footer_audited: "100% व्यक्तिगत ऑडिट",
    footer_zero_brokerage_badge: "शून्य ब्रोकरेज",
    footer_copyright: "रूमनेस्ट इंडिया। देश भर के कॉलेज छात्रों के लिए बनाया गया।",
    footer_safety: "सुरक्षा मानक",
    footer_rent_support: "किराया समझौता सहायता",
    search_results: "खोज परिणाम",
    filters: "फ़िल्टर",
    sort_by: "क्रम से",
    distance_low: "दूरी: कम से ज़्यादा",
    price_low: "किराया: कम से ज़्यादा",
    price_high: "किराया: ज़्यादा से कम",
    rating_high: "रेटिंग: ज़्यादा से कम",
    newest_first: "नवीनतम पहले",
    campus_college: "कैंपस / कॉलेज",
    room_type: "कमरे का प्रकार",
    occupancy_type: "ऑक्यूपेंसी",
    max_distance: "अधिकतम दूरी",
    price_range: "किराया सीमा",
    min_rent: "न्यूनतम किराया",
    max_rent: "अधिकतम किराया",
    amenities: "सुविधाएं",
    food_included_filter: "भोजन / मेस शामिल",
    verified_only: "केवल सत्यापित",
    rent_agreement: "किराया समझौता",
    apply_filters: "फ़िल्टर लागू करें",
    clear_all: "सभी हटाएं",
    showing_results: "परिणाम दिखा रहे हैं",
    no_rooms_found: "कोई कमरा नहीं मिला",
    try_different: "अलग फ़िल्टर या सर्च शब्द आज़माएं",
    load_more: "और लोड करें",
    ai_name: "RoomBuddy",
    ai_tagline: "AI कमरा खोज सहायक",
    ai_greeting: "नमस्ते! मैं RoomBuddy हूं। मैं आपको सही PG या कमरा खोजने में मदद कर सकता हूं। 'GEC के पास लड़कों का PG दिखाओ' या '4000 से कम किराये वाले कमरे' बोलकर देखें!",
    ai_listening: "सुन रहा हूं... अब बोलें",
    ai_placeholder: "कमरा खोजने के लिए लिखें या बोलें...",
    ai_speak: "बोलें",
    ai_close: "बंद करें",
    ai_quick_boys: "कैंपस के पास लड़कों का PG",
    ai_quick_girls: "भोजन वाला लड़कियों का PG",
    ai_quick_budget: "4000 से कम कमरे",
    ai_quick_single: "प्राइवेट सिंगल रूम",
  },

  "hi-en": {
    brand_sub: "Verified PGs & Co-Living",
    explore_pgs: "PGs Explore Karein",
    find_roommates: "Roommate Khojein",
    how_it_works: "Ye Kaise Kaam Karta Hai",
    list_your_pg: "Apna PG List Karein",
    admin_panel: "Admin Panel",
    sign_in: "Sign In",
    student_signup: "Student Sign Up",
    logout: "Log Out",
    my_dashboard: "Mera Dashboard",
    select_campus: "Campus / Area Chunein",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    hero_title: "Verified Student Living",
    co_living: "Apne Campus Ke Paas",
    hero_subtitle: "42-point physical safety check se verified student PGs, hostels aur private rooms dhoondhein. Zero brokerage guaranteed.",
    search_placeholder: "College, gate ya locality enter karein (jaise GEC Kumarbagh)...",
    search_btn: "Verified Rooms Dhoondhein",
    zero_brokerage: "Zero Brokerage",
    verified_rooms: "Verified Accommodation",
    trust_pill: "100% In-Person Audited Accommodations • Zero Brokerage Guarantee",
    near_live_location: "Meri Live Location Ke Paas (10 km)",
    popular_label: "Popular:",
    popular_campuses_dropdown: "Popular Campuses & Cities",
    all_gender: "Sabhi Types (Boys / Girls / Co-ed)",
    boys_only: "Sirf Boys",
    girls_only: "Sirf Girls",
    co_ed: "Co-ed Living",
    any_budget: "Koi Bhi Budget",
    metric_beds: "Verified Student Beds",
    metric_brokerage: "Zero Brokerage Always",
    metric_reviews: "Student Reviews",
    metric_audit: "42-Point Physical Audit",
    popular_accommodation_types: "Popular Accommodation Types",
    explore_verified_rooms: "Aapke lifestyle aur budget ke hisaab se verified rooms.",
    browse_all: "Sab Dekhein",
    boys_pg_hostels: "Boys PG & Hostels",
    boys_pg_desc: "3 time khana, Wi-Fi & padhai ka mahaul",
    boys_only_tag: "Boys Only",
    girls_pg_hostels: "Girls PG & Hostels",
    girls_pg_desc: "Safe, gated campus, 24x7 warden & CCTV",
    girls_safe_tag: "100% Safe & Gated",
    pg_with_meals: "3 Time Khana Wala PG",
    pg_meals_desc: "Nashta, lunch aur dinner included",
    homely_food_tag: "Ghar Jaisa Khana",
    private_rooms: "Private Single Rooms",
    private_rooms_desc: "Attached bathroom ke saath apna room",
    full_privacy_tag: "Full Privacy",
    explore_by_city: "City & Campus Ke Hisaab Se PGs Dekhein",
    explore_by_city_sub: "Campus gates ke paas verified student PGs aur hostels dhoondhein.",
    verified_pgs_near: "Aapke Paas Verified PGs & Co-Living",
    verified_pgs_sub: "100% Verified owners • Physical inspection done • Direct WhatsApp owners se",
    all_pgs: "Sabhi PGs",
    meals_included: "Khana Included",
    boys_pg: "Boys PG",
    girls_pg: "Girls PG",
    single_room: "Single Room",
    no_match_filter: "Is filter se koi room nahi mila",
    reset_filters: "Filters Reset Karein",
    audit_badge: "RoomNest 5-Point Audit Standard",
    audit_title: "List Karne Se Pehle Hum Kya Check Karte Hain",
    audit_sub: "Har PG ki building, bedroom, study desk, washroom aur mess khane ki physical checking hoti hai.",
    genuine_photos: "100% Asli Photos",
    audit_1: "1. Building Ka Front Look",
    audit_1_sub: "Gated entry, street lighting & curfew gate",
    audit_2: "2. Clean Student Bedroom",
    audit_2_sub: "Comfortable mattress, ventilation & wardrobe",
    audit_3: "3. Study Table & Wi-Fi",
    audit_3_sub: "Study desk, lamp & 50+ Mbps internet",
    audit_4: "4. Attached Washroom",
    audit_4_sub: "Clean tiles, running water & hot geyser",
    audit_5: "5. Hygienic Mess Hall",
    audit_5_sub: "Fresh khana, dining tables & UV/RO paani",
    inspected_by: "Campus Team Ne Check Kiya",
    advantage_label: "RoomNest Advantage",
    advantage_title: "Students & Parents RoomNest Par Trust Kyun Karte Hain",
    advantage_sub: "Hum student housing ki sabse badi problems ko transparency se solve karte hain.",
    verified_owners: "100% Verified Owners",
    verified_owners_desc: "Har owner ka government ID (Aadhaar/PAN) aur in-person property audit se verification.",
    zero_brokerage_title: "Hamesha Zero Brokerage",
    zero_brokerage_desc: "Koi dalal nahi. WhatsApp pe owner se seedhe baat karein, full rent transparency.",
    homely_meals: "Ghar Jaisa 3 Time Khana & RO Water",
    homely_meals_desc: "Weekly audited mess, fresh sabziyaan, hygienic kitchen, aur UV+RO drinking water.",
    safe_campus: "Safe Gated Campus",
    safe_campus_desc: "Street lighting, night curfew, CCTV cameras, aur 24/7 security guards.",
    faq_label: "Koi Sawaal Hai?",
    faq_title: "Aksar Poochhe Jaane Waale Sawaal",
    faq_1_q: "RoomNest PG owners aur properties ko kaise verify karta hai?",
    faq_1_a: "RoomNest pe listed har room ki campus team dwara 5-point physical audit hoti hai. Hum owner ka government ID, building gate, bedroom furniture, study table, geyser verify karte hain aur mess ka khana taste karke hi listing approve karte hain.",
    faq_2_q: "Kya koi brokerage fee hai?",
    faq_2_a: "Zero! Bilkul Rs.0 brokerage. Aap seedhe verified owner ya warden se WhatsApp ya call pe contact karein, full price transparency ke saath.",
    faq_3_q: "Kya main apni live location se 10 km ke andar rooms dhundh sakta/sakti hoon?",
    faq_3_a: "Haan! 'Meri Live Location Ke Paas' button ya search bar mein GPS icon pe click karein. Platform automatically distance calculate karke 10 km ke andar verified PGs dikhayega.",
    faq_4_q: "Kya PGs college address proof ke liye rent agreement dete hain?",
    faq_4_a: "Haan, hamare verified partner PGs move-in pe formal rent agreement dete hain, jise students college registration, bank accounts, ya scholarship applications ke liye submit kar sakte hain.",
    cta_label: "PG Owners & Wardens Ke Liye",
    cta_title: "Campus ke paas student PG ya hostel hai?",
    cta_desc: "Free mein list karein, hamare audit team se verification karwayen, aur 1,000+ students se seedhe WhatsApp inquiries paayein. Zero listing fee.",
    cta_btn: "Free Mein PG List Karein",
    campus_proximity: "Campus Proximity",
    live_map_title: "Live GPS Route & Distance Map",
    live_location: "Aapki Live Location",
    room_location: "Selected Room",
    campus_gate: "College / University Gate",
    distance_you_to_room: "Aapki Location Se Room Tak",
    distance_room_to_campus: "Room Se College Gate Tak",
    walking_time: "Paidal Time",
    cycling_time: "Cycle Se",
    driving_transit: "Bike / Auto",
    gps_active: "Live GPS Connected",
    gps_locating: "Location track ho rahi hai...",
    gps_enable: "Live GPS On Karein",
    gps_refresh: "GPS Refresh Karein",
    google_maps_route: "Google Maps Par Route Dekhein",
    to_room_directions: "Room Tak Ka Route",
    to_campus_directions: "College Tak Ka Route",
    schedule_visit_title: "Free Visit Schedule Karein",
    book_visit_slot: "Visit Slot Book Karein",
    visit_success_msg: "Visit schedule ho gayi! Owner ko WhatsApp pe notification chala gaya.",
    verified_owner: "Verified Room Owner",
    call_owner: "Call Owner",
    whatsapp_owner: "WhatsApp",
    in_app_chat: "Chat Karein",
    rent_breakdown: "Total Rent Breakdown",
    per_month: "/ month",
    deposit: "Security Deposit",
    food_included: "Food / Mess Included",
    curfew_timing: "Curfew & Gate Timings",
    facilities: "Student Facilities",
    write_review: "Review Likhein",
    verified_owner_badge: "100% Verified Owner",
    meals_included_badge: "3 Meals Included",
    walk_min: "min walk",
    per_mo: "/mo",
    view_details: "Details Dekhein",
    whatsapp_now: "WhatsApp Karein",
    compare: "Compare Karein",
    zero_brokerage_badge: "Zero Brokerage",
    food_mess: "Khana/Mess",
    study_desk: "Study Desk",
    wifi_label: "Wi-Fi",
    beds_available: "beds available",
    login_title: "Student & Owner Login",
    login_sub: "Verified listings, campus visits aur owner chats access karein.",
    email_placeholder: "Email address",
    password_placeholder: "Password",
    forgot_password: "Password bhool gaye?",
    login_btn: "Log In Karein",
    logging_in: "Login ho raha hai...",
    new_to_roomnest: "RoomNest pe naye hain?",
    create_account: "Account banayein",
    register_title: "Apna Account Banayein",
    register_sub: "Sahi room dhoondhne ke liye RoomNest se judein",
    full_name: "Poora Naam",
    phone_number: "Phone Number",
    confirm_password: "Password Confirm Karein",
    register_as: "Register karein as",
    student_tenant: "Student / Tenant",
    pg_owner: "PG Owner / Warden",
    register_btn: "Account Banayein",
    registering: "Account ban raha hai...",
    already_have_account: "Pehle se account hai?",
    sign_in_link: "Sign In Karein",
    footer_popular_campuses: "Popular Campuses",
    footer_student_living: "Student Living",
    footer_find_rooms: "Campus Rooms Dhoondhein",
    footer_find_roommate: "Roommate Dhoondhein",
    footer_rent_guide: "Rent Agreement Guide",
    footer_zero_brokerage: "Zero Brokerage Policy",
    footer_owners: "Property Owners & Staff",
    footer_list_pg: "Student PG / Room List Karein",
    footer_owner_verify: "Owner Verification Process",
    footer_owner_dashboard: "Owner Dashboard",
    footer_admin_portal: "Admin Approval Portal",
    footer_tagline: "Verified Student Accommodations",
    footer_desc: "College students ko zero brokerage, transparent mess & utility costs, aur student peer reviews ke saath verified PGs, hostels, aur rental rooms dhoondhne mein madad.",
    footer_audited: "100% In-Person Audited",
    footer_zero_brokerage_badge: "Zero Brokerage",
    footer_copyright: "RoomNest India. College students ke liye banaya gaya.",
    footer_safety: "Safety Standards",
    footer_rent_support: "Rent Agreement Support",
    search_results: "Search Results",
    filters: "Filters",
    sort_by: "Sort By",
    distance_low: "Distance: Kam Se Zyada",
    price_low: "Rent: Kam Se Zyada",
    price_high: "Rent: Zyada Se Kam",
    rating_high: "Rating: Zyada Se Kam",
    newest_first: "Newest Pehle",
    campus_college: "Campus / College",
    room_type: "Room Type",
    occupancy_type: "Occupancy",
    max_distance: "Max Distance",
    price_range: "Rent Range",
    min_rent: "Min Rent",
    max_rent: "Max Rent",
    amenities: "Suvidhayen",
    food_included_filter: "Khana / Mess Included",
    verified_only: "Sirf Verified",
    rent_agreement: "Rent Agreement",
    apply_filters: "Filters Apply Karein",
    clear_all: "Sab Hatayein",
    showing_results: "Results dikha rahe hain",
    no_rooms_found: "Koi room nahi mila",
    try_different: "Alag filters ya search words try karein",
    load_more: "Aur Load Karein",
    ai_name: "RoomBuddy",
    ai_tagline: "AI Room Finding Assistant",
    ai_greeting: "Namaste! Main RoomBuddy hoon. Main aapko perfect PG ya room dhoondhne mein help karunga. 'GEC ke paas boys PG dikhao' ya '4000 se kam ka room' bol ke dekhein!",
    ai_listening: "Sun raha hoon... Ab bolein",
    ai_placeholder: "Room dhoondhne ke liye likhein ya bolein...",
    ai_speak: "BOLEIN",
    ai_close: "Band Karein",
    ai_quick_boys: "Campus ke paas boys PG",
    ai_quick_girls: "Khana wala girls PG",
    ai_quick_budget: "Rs.4000 se kam rooms",
    ai_quick_single: "Private single rooms",
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  languages: [],
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const saved = localStorage.getItem("roomnest_lang");
      if (saved && translations[saved]) return saved;
    } catch {
      // ignore
    }
    return "en";
  });

  function setLanguage(lang) {
    if (translations[lang]) {
      setLanguageState(lang);
      try {
        localStorage.setItem("roomnest_lang", lang);
      } catch {
        // ignore
      }
    }
  }

  function t(key, fallback = "") {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || fallback || key;
  }

  const languages = [
    { code: "en", label: "English", short: "EN", flag: "\u{1F1EC}\u{1F1E7}" },
    { code: "hi", label: "\u0939\u093F\u0902\u0926\u0940", short: "HI", flag: "\u{1F1EE}\u{1F1F3}" },
    { code: "hi-en", label: "Hinglish", short: "HIN", flag: "\u{1F1EE}\u{1F1F3}" },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
